### ISSUE TITLE
Improve system tests

### ISSUE THREAD

**Issue by meator** [enkore/j4-dmenu-desktop#188]
I have been working on this feature for some time now. It requires more work though and I don't want to delay r3.2 further.

The current pytest testsuite is written in a DRY fashion. It is not really readable because of this. A solution I have been toying with is making a YAML file which would define all tests and their environment. This file would be more readable than the current Python code. Here is an example of how such a file could look like:

```yaml
description: "Test --help flag"
test: exit_status
args: [--help]
---
description: Test --version flag
test: exit_status
args: [--version]
---
# TODO: chdir
description: Regression test faulty SearchPath checks
test: exit_status
environmental_variables:
  XDG_DATA_HOME: "$empty_directory$"
  XDG_DATA_DIRS: .:a:b
args: [--version]
---
description:
  Test j4-dmenu-desktop's integration with its supported terminal emulators
parametrize_from_dict: "#terminal-emulator-matrix#"
parametrize_skip:
  # TODO: Maybe unify two dicts
  - terminator:
      skip_message: See https://github.com/gnome-terminator/terminator/issues/923
condition:
  function: check_term_emulator_availability
  kw_args:
    terminal_name: "@parametrize.terminal_name@"
    commandline_flag: "@parametrize.commandline_flag@"
test:
  type: external_function
  function: test_term_emulator
  kw_args:
    tested_string: "#bad-strings#"
environmental_variables:
  PATH: "$helpers_path$:$PATH_list$"
  XDG_DATA_HOME: "$test_files$"
  XDG_DATA_DIRS: "$empty_directory$"
args: [--dmenu, "$dmenu_selected_imitator_helper$", --term-mode, "@parametrize@", --strict]
```

 I make use of [pytest's capabilities of testing non-Python code](https://docs.pytest.org/en/stable/example/nonpython.html) to read YAML and convert into unit tests. The tests themselves (mainly the more complicated ones) would be defined in a separate `definitions.py` file that would only include the testing function, which would receive a `J4ddExecutor` Python class instance which would have environment prefilled from the YAML file.

I wonder if there's a good library/framework for this. My solution would triple the code size for `tests/system_tests/`, but the definition files would be cleaner.
